# This is a basic workflow to help you get started with Actions

# このワークフローの名前
name: CI

# このワークフローが実行される条件
# -----------------------------------------
on:
  # プッシュされた時
  push:
    # なかでもmainブランチがブッシュされたとき
    branches: [ "main" ]
  # メインブランチにプルリクエストが来たとき
  pull_request:
    branches: [ "main" ]

  # ワークフロー実行ボタンが押された時
  workflow_dispatch:

# このワークフローが実行された時の処理
# ----------------------------------------

# すべてのジョブ
jobs:
  # ジョブの名前
  build:
    # ジョブを実行する環境
    runs-on: ubuntu-latest

    # このジョブが順次実行するステップ
    steps:
      # このリポジトリをクローン
      - uses: actions/checkout@v3

      # ステップの名前
      - name: Run a one-line script
      # ステップの処理
        run: echo Hello, world!

      # ステップの名前
      - name: Run a multi-line script
      # ステップの処理
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  # ジョブの名前
  newJob:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
